resolver: lts-8.3

packages:
- .
- location:
    git: https://github.com/clash-lang/ghc-typelits-extra.git
    commit: 4ed53dcf9065bc66f7a19030247f4698e688794a
  extra-dep: true
- location:
    git: https://github.com/clash-lang/ghc-typelits-knownnat.git
    commit: a1af2abb705349b4c5c5843346bf998e13849cfb
  extra-dep: true
- location:
    git: https://github.com/clash-lang/ghc-typelits-natnormalise.git
    commit: f81d6841edd6baea23dbe0ff9a896571d0e72d09
  extra-dep: true

flags:
  clash-prelude:
    doclinks: true
